info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local
    metrics:
        prometheus:
            timerPercentilesMax: "PT5S"
            timerPercentilesMin: "PT0.1S"
aurora:
  starter:
    headerfilter:
      enabled: false

logging:
  level:
    no.skatteetaten.aurora.mokey: DEBUG
    org:
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: WARN
        velocity: WARN
  pattern:
    console: "%d [%thread] %-5level %logger:%L %X - %msg %n%rEx{full}"

---
spring:
    profiles: local

logging:
    pattern:
      console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties


---
spring:
  profiles: openshift
