info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    config:
        activate:
            on-profile: default
    codec:
        max-in-memory-size: -1 # Unlimited


logging:
    level:
        reactor.netty.http.client: ERROR
        no.skatteetaten.aurora: INFO
        org:
            hibernate: WARN
            springframework: WARN
            apache:
                coyote: WARN
                catalina: WARN
                velocity: WARN

management:
    metrics:
        distribution:
            minimum-expected-value:
                http: 50ms
            maximum-expected-value:
                http: 3s

integrations:
    boober:
        url: "http://boober"
    splunk:
        url: "https://splunk.skead.no"
    metrics:
        url: "http://metrics.skead.no"
    cantus:
        url: "http://cantus"

openshift:
    cluster: utv
    port: 8443
    url: https://${openshift.cluster}-master.paas.skead.no:${openshift.port}

kubernetes:
    timeout:
        connect: 1s
        read: 10s
    retry:
        times: 3
        min: 100ms
        max: 2s
mokey:
    cachewarmup:
        enabled: false
---
spring:
    sleuth:
        enabled: false
    config:
        activate:
            on-profile: openshift

logback:
    access:
        config: file:${logback.access.b3}

logging.level.reactor.netty.http.client: ERROR
