info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local
    codec:
        max-in-memory-size: -1 # Unlimited


logging:
    level:
        reactor.netty: ERROR
        no.skatteetaten.aurora: INFO
        org:
            hibernate: WARN
            springframework: WARN
            apache:
                coyote: WARN
                catalina: WARN
                velocity: WARN

management:
    metrics:
        distribution:
            minimum-expected-value:
                http: 50ms
            maximum-expected-value:
                http: 3s

integrations:
    boober:
        url: "http://boober"
    splunk:
        url: "https://splunk.skead.no"
    metrics:
        url: "http://metrics.skead.no"
    cantus:
        url: "http://cantus"

openshift:
    cluster: utv
    port: 8443
    url: https://${openshift.cluster}-master.paas.skead.no:${openshift.port}

kubernetes:
    timeout:
        connect: 1s
        read: 10s
    retry:
        times: 3
        min: 100ms
        max: 2s
---
spring:
    profiles: local

mokey:
    cachewarmup:
        enabled: true
    cache:
        affiliations: safir

integrations:
    cantus:
        url: http://cantus.aurora.utv.paas.skead.no
logging:
    pattern:
        console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties
    level:
        no.skatteetaten.aurora: DEBUG

kubernetes:
    url: https://${openshift.cluster}-master.paas.skead.no:${openshift.port}
    tokenLocation: /tmp/reader-token

---
spring:
    profiles: openshift
    zipkin:
        enabled: false
    sleuth:
        enabled: false

logback:
    access:
        config: file:${logback.access.b3}
