openshift:
    cluster: utv04
    port: 6443
integrations:
    boober:
        url: https://boober-aup.apps.utv04.paas.skead.no
    metrics:
        url: http://metrics.skead.no
    splunk:
        url: http://splunk.skead.no
    cantus:
        url: https://cantus-aup.apps.utv04.paas.skead.no

mokey:
    cachewarmup:
        enabled: true
    cache:
        affiliations: aup

logging:
    pattern:
        console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties
    level:
        no.skatteetaten.aurora: DEBUG
        reactor.netty.http.client: ERROR

kubernetes:
    url: https://api.${openshift.cluster}.paas.skead.no:${openshift.port}
    tokenLocation: /tmp/reader-token