info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local

logging:
    level:
        no.skatteetaten.aurora:
            mokey: INFO
        org:

            hibernate: WARN
            springframework: WARN
            apache:
                coyote: WARN
                catalina: WARN
                velocity: WARN

integrations:
    boober:
        url: "http://boober"
    splunk:
        url: "https://splunk.skead.no"
    metrics:
        url: "http://metrics.skead.no"

management:
    metrics:
        enable:
            http:
                client: false
---
spring:
    profiles: local

mokey:
    cache:
        affiliations: paas, aurora
    openshift:
        tokenLocation: file:/tmp/boober-token

logging:
    pattern:
        console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties
    level:
        no.skatteetaten.aurora:
            mokey: DEBUG

openshift-cluster: utv
openshift.cluster: utv

---
spring:
    profiles: openshift
